config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :offers
  end

  namespace :member do
    resources :offers
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :starts_at, presence: true
  validates :advertiser_name, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 500, too_long: "%{count} characters is the maximum allowed" }
  validates :url, presence: true, format: URI::regexp(%w[http https])

  scope :active, -> { where('starts_at <= ? and (ends_at IS NULL OR ends_at >= ? )', DateTime.current, DateTime.current) }
  scope :ordered_by_premium, -> { order(premium: :desc) }

  def enabled
    return true if ends_at.nil?

    now = DateTime.current
    starts_at <= now && ends_at >= now
  end
end

app/controllers/admin/offers_controller.rb
module Admin
  class OffersController < ApplicationController
    before_action :set_offer, only: [:edit, :update, :destroy]

    def index
      @offers = Offer.all
    end

    def new
      @offer = Offer.new
    end

    def create
      @offer = Offer.new(offer_params)
      if @offer.save
        redirect_to admin_offers_path, flash: { success: 'Offer created!' }
      else
        render :new
      end
    end

    def edit
      @offer = Offer.find(params[:id])
    end

    def update
      if @offer.update(offer_params)
        redirect_to admin_offers_path, notice: 'Offer was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @offer.destroy
      redirect_to admin_offers_path, notice: 'Offer was successfully destroyed.'
    end

    private

    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(
        :advertiser_name,
        :url,
        :description,
        :starts_at,
        :ends_at,
        :premium
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/member/offers_controller.rb
module Member
  class OffersController < ApplicationController
    def index
      @offers = Offer.active.ordered_by_premium
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/offers/_form.erb
<% if @offer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
    <ul>
    <% @offer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :advertiser_name %>
  <%= f.text_field :advertiser_name, class: 'form-control'%>
</div>

<div class="form-group">
  <%= f.label :url, 'Url *'%>
  <%= f.url_field :url, class: 'form-control'%>
</div>

<div class="form-group">
  <%= f.label :description, 'Description *'%>
  <%= f.text_area :description, class: 'form-control'%>
</div>

<div class="form-group">
  <%= f.label :starts_at, 'Starts at *'%>
  <%= f.date_field :starts_at, class: 'form-control'%>
</div>

<div class="form-group">
  <%= f.label :ends_at, 'End at'%>
  <%= f.date_field :ends_at, class: 'form-control'%>
</div>

<div class="form-group">
  <%= f.check_box :premium, class: ''%>
  <%= f.label :premium, 'Premium' %>
</div>

<div class="form-group">
  <%= f.submit "Enviar", class: "btn btn-primary" %>
</div>

app/views/admin/offers/edit.erb
<h1>Edit Offer</h1>

<%= form_for @offer, url: "#{admin_offers_path}/#{@offer.id}" do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/admin/offers/index.erb
<h1>Offers</h1>

<%= link_to "New Offer", new_admin_offer_path,  class: "btn btn-primary" %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>id</th>
    <th>name</th>
    <th>url</th>
    <th>status</th>
    <th>actions</th>
  </tr>
  </thead >
  <tbody>
  <% @offers.each do |offer| %>
    <tr>
      <td><%= offer.id %></td>
      <td><%= offer.advertiser_name %></td>
      <td><%= offer.url %></td>
      <td><%= offer.enabled ? 'enabled' : 'disabled' %>
      </td>
      <td>
        <%= link_to '[edit]', edit_admin_offer_path(offer), class: 'btn btn-info' %>
        <%= link_to "#{offer.enabled ? '[disable]' : '[enabled]' }", edit_admin_offer_path(offer), class: 'btn btn-info' %>
        <%= link_to '[destroy]', admin_offer_path(offer), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/offers/new.erb
<h1>New Offer</h1>

<%= form_for @offer, url: admin_offers_path do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lemoney</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/member/offers/index.erb
<section>
  <div class="card-container">
    <% @offers.each do |offer| %>
      <div class='custom-card'>
        <% if offer.premium %>
          <span class='premium-tag'>
            premium
          </span>
        <% end %>

        <div class='card-item'>
          <%= offer.advertiser_name %>
        </div>

        <div class='card-item'>
          <a href='<%= offer.url%>' class='btn <%= offer.enabled ? 'btn-success' : 'btn-default' %>'>
            Shop now
          </a>
        </div>
      </div>
    <% end %>
  </div>
</section>